### ISSUE TITLE
Files screen hiccups

### ISSUE THREAD

**Issue by macmpi** [rbackhouse/MaximumMPD#37]
Files screen does not seem always properly refreshed, unlike main Play screen.
It seems ok at first launch, but if iPhone sleeps and reconnect, then File view is empty.
(BTW avahi discovery still has issues when app is "terminated" and then re-opened)

In addition, files are shown with actual filenames in Files screen, rather than by their track name (if available).
Once in the play Queue, they show fine by their track name.
Would be nice to have it consistent.
Thanks!

**Comment by rbackhouse** [comment]
There was a bug I fixed a while back with files disappearing after a sleep/reconnect.

Can you tell me what type of device you are using and its iOS version. 

I have seen some slowness with discovery on older devices (iphone 5s) but all my servers eventually show up discovered.

Re the File screen showing track names I've opened and enhancement to hande that https://github.com/rbackhouse/MaximumMPD/issues/38

**Comment by macmpi** [comment]
I used to have a 4S 9.3.6, and now SE 2020 on 13.4.1 (quite a bump!).
I am still having some discovery problems with the latter (less, but still).

**Comment by rbackhouse** [comment]
To clarify when you say the view is empty it's only files that are missing not directories. I can intermittently recreate that scenario.

**Comment by macmpi** [comment]
no, even directories may be missing

**Comment by macmpi** [comment]
In fact, that view does not appear to be refreshed, unlike tabs in Player views.
It keeps it's content from initial connection.

For instance, modify/remove files on server from another client, you will still see them.

**Comment by rbackhouse** [comment]
For the discovery problems I have opened up a new issue. Support rescanning of discovered MPD servers #39

For the Files refresh issue I have opened Files screen does not refresh when it gains focus #40
however directory and file modifications/removal will not been seen unless an "update" command is run.

**Comment by macmpi** [comment]
> directory and file modifications/removal will not been seen unless an "update" command is run first.

sure.
Thanks.

**Comment by rbackhouse** [comment]
With the recent updates have you seen any improvements on File showing up empty ?

**Comment by macmpi** [comment]
Seems much better since last 2 versions I think, thanks.
Only missing bit now is to show them with their actual track names (if avail) rather than file name (like it does once in queue).

**Comment by rbackhouse** [comment]
https://github.com/rbackhouse/MaximumMPD/issues/38 and https://github.com/rbackhouse/MaximumMPD/issues/36 will be in the next release. Sounds like this one can be closed
